#!/usr/bin/env python3
from __future__ import annotations

import math
import time
from datetime import datetime

from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

state = {
    "speed": 78, "rpm": 9200, "temp": 96.0, "delta": 0.184,
    "sectors": [18.42, 22.18, 16.77], "best_lap": 57.12,
    "last_lap": 57.37, "ideal_lap": 56.84,
    "circuit": "Pista demo", "driver": "Driver 01", "gps": "10/12", "sat": "12",
    "event_id": 0, "last_event_at": 0.0, "event_step": 0, "sector_event": None,
}

HTML = r'''
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#000000"><title>Kart Performance Monitor</title><style>
:root{--white:#f4f4f4;--muted:#c8c8c8;--purple:#d500f9;--green:#00a651;--yellow:#d9a300}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000;color:#fff;font-family:Arial,Helvetica,sans-serif}body{display:grid;place-items:center}
.dashboard{width:100vw;height:100vh;max-width:932px;max-height:430px;padding:10px 20px 4px;display:grid;grid-template-columns:1fr 1.46fr 1fr;gap:12px;background:#000}.column{min-width:0;display:flex;flex-direction:column}.topbar{grid-column:1/-1;height:21px;display:flex;justify-content:space-between;align-items:center;font-size:11px;line-height:13px;font-weight:700;white-space:nowrap}.topbar-left,.topbar-right{display:flex;align-items:center;gap:18px}.topbar-left{margin-left:10px}.topbar-right{gap:13px;margin-right:10px}.dashboard{grid-template-rows:21px minmax(0,1fr)}.column{grid-row:2}
.panel{position:relative;min-height:0;height:100%;border:2px solid var(--white);border-radius:23px}.panel-title{position:absolute;z-index:3;top:-10px;left:50%;transform:translateX(-50%);padding:0 10px;background:#000;white-space:nowrap;font-size:12px;font-weight:800}.left-panel{display:flex;flex-direction:column;gap:8px;padding:29px 14px 9px}.box{border:2px solid var(--white);border-radius:20px;padding:10px 15px;min-height:64px}.box-title{margin:0;text-align:center;font-size:11px;font-weight:800}#delta{padding-top:8px;text-align:center;font-size:18px;font-weight:800}.delta-positive{color:#ffb7b7}.delta-negative{color:#bfffc5}.sector{width:calc(100% - 17px);margin-left:17px;min-height:92px}.sector-values{margin-top:8px;font-size:14px;font-weight:800;line-height:21px}.sector-values span{float:right;font-size:15px}
/* Modalità grandi e spostate leggermente più verso il basso. */
.modes{display:grid;gap:7px;padding:0 16px;margin-top:auto;margin-bottom:11px}.mode{height:25px;border:2px solid var(--white);border-radius:14px;display:grid;place-items:center;font-size:11px;font-weight:800;letter-spacing:.1px}.mode.active{background:#fff;color:#000}
.telemetry-panel{padding:27px 30px 9px;display:flex;flex-direction:column;align-items:center}.gauge{width:100%}.gauge-track{height:32px;position:relative;border:2px solid var(--white);background:linear-gradient(90deg,#fff 0 var(--fill,0%),transparent var(--fill,0%))}.gauge-track:after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 13px,#fff 13px 15px);opacity:.82}.needle{position:absolute;z-index:2;top:-10px;height:46px;border-left:3px solid #fff;transition:left .5s}.needle:before{content:"";position:absolute;top:-8px;left:-7px;border-left:7px solid transparent;border-right:7px solid transparent;border-top:9px solid #fff}.gauge-labels{display:flex;justify-content:space-between;margin-top:4px;font-size:11px;font-weight:700}.unit{text-align:center;margin-top:2px;color:var(--muted);font-size:10px;font-weight:700}.speed-row{display:flex;align-items:baseline;gap:13px;margin:auto 0 14px}#speed{font-size:124px;letter-spacing:-7px;line-height:.7;font-weight:800}.speed-caption{font-size:20px;line-height:20px;font-weight:800}.speed-caption small{font-size:18px;font-weight:500}.temp-gauge{width:92%;margin-top:auto}.temp-gauge .gauge-track{height:16px}.temp-gauge .needle{top:-7px;height:30px}.temp-gauge .gauge-labels{font-size:10px}
.right-panel{padding:65px 13px 9px}.lap-box{height:58px;min-height:0;margin-bottom:9px;display:flex;flex-direction:column;justify-content:center}.lap-time{margin-top:5px;text-align:center;font-size:18px;font-weight:800}
.sector-popup{position:fixed;z-index:30;left:50%;top:50%;width:min(53vw,495px);height:min(27vw,240px);min-width:380px;min-height:178px;transform:translate(-50%,-50%) scale(.92);display:grid;place-items:center;text-align:center;border:5px solid #fff;border-radius:30px;opacity:0;visibility:hidden;pointer-events:none;box-shadow:0 0 38px rgba(255,255,255,.30);transition:opacity .18s ease,transform .18s ease,visibility .18s}.sector-popup.show{opacity:1;visibility:visible;transform:translate(-50%,-50%) scale(1)}.sector-popup.purple{background:var(--purple)}.sector-popup.green{background:var(--green)}.sector-popup.yellow{background:var(--yellow)}.popup-result{padding:8px 18px;color:#fff;font-size:clamp(55px,10vw,94px);line-height:1;font-weight:900;letter-spacing:-2px;font-variant-numeric:tabular-nums;white-space:nowrap;text-shadow:0 3px 1px rgba(0,0,0,.2)}
@media(max-height:390px){.dashboard{padding-top:6px;grid-template-rows:18px minmax(0,1fr)}.topbar{height:18px}.left-panel{padding-top:25px}.telemetry-panel{padding-top:24px}.right-panel{padding-top:56px}#speed{font-size:114px}.lap-box{height:53px!important;margin-bottom:7px!important}.mode{height:21px;font-size:10px}.modes{gap:4px;padding:0 20px;margin-bottom:8px}.sector{width:calc(100% - 14px);margin-left:14px}.sector-values{font-size:13px}.sector-values span{font-size:14px}.sector-popup{height:185px}}@media(max-width:700px){.dashboard{padding-left:12px;padding-right:12px;gap:8px}.topbar-left{gap:10px;margin-left:7px}.topbar-right{gap:8px;margin-right:7px}.sector-popup{width:84vw;height:48vw;min-width:0;min-height:0}.popup-result{font-size:17vw}}
</style></head><body>
<main class="dashboard"><div class="topbar"><div class="topbar-left"><span>Circuit: <span id="circuit"></span></span><span>Driver: <span id="driver"></span></span></div><div class="topbar-right"><span>GPS: <span id="gps"></span></span><span>SAT: <span id="sat"></span></span></div></div>
<section class="column"><div class="panel left-panel"><div class="panel-title">SECTOR</div><div class="box"><h2 class="box-title">DELTA TIME <span style="font-size:8px;letter-spacing:.6px">LIVE</span></h2><div id="delta">+0.000 s</div></div><div class="box sector"><h2 class="box-title">LAST SECTOR</h2><div class="sector-values">S1 <span id="s1">--</span><br>S2 <span id="s2">--</span><br>S3 <span id="s3">--</span></div></div><div class="modes"><div class="mode">WARM UP</div><div class="mode active">HAMMER TIME</div><div class="mode">COOL DOWN</div></div></div></section>
<section class="column"><div class="panel telemetry-panel"><div class="panel-title">TELEMETRY</div><div class="gauge"><div class="gauge-track" id="rpmTrack"><div class="needle" id="rpmNeedle"></div></div><div class="gauge-labels"><span>0</span><span>2</span><span>4</span><span>6</span><span>8</span><span>10</span><span>12</span><span>14</span><span>16</span><span>18</span><span>20</span></div><div class="unit">RPM (x1000)</div></div><div class="speed-row"><strong id="speed">0</strong><div class="speed-caption">SPEED<br><small>km/h</small></div></div><div class="gauge temp-gauge"><div class="gauge-track" id="tempTrack"><div class="needle" id="tempNeedle"></div></div><div class="gauge-labels"><span>20°C</span><span>40°C</span><span>60°C</span><span>80°C</span><span>100°C</span><span>120°C</span><span>150°C</span></div><div class="unit">TEMP (°C)</div></div></div></section>
<section class="column"><div class="panel right-panel"><div class="panel-title">LAP</div><div class="box lap-box"><h2 class="box-title">BEST LAP</h2><div id="bestLap" class="lap-time">--:--.---</div></div><div class="box lap-box"><h2 class="box-title">LAST LAP</h2><div id="lastLap" class="lap-time">--:--.---</div></div><div class="box lap-box"><h2 class="box-title">IDEAL LAP</h2><div id="idealLap" class="lap-time">--:--.---</div></div></div></section></main>
<div id="sectorPopup" class="sector-popup"><div id="popupResult" class="popup-result">+0.000 s</div></div>
<script>
const fmt=v=>{const m=Math.floor(v/60),s=v-m*60;return `${m}:${s.toFixed(3).padStart(6,'0')}`};const gauge=(t,n,p)=>{p=Math.max(0,Math.min(100,p));t.style.setProperty('--fill',p+'%');n.style.left=p+'%'};let lastEventId=0,popupTimer=null;function showPopup(event){const p=document.getElementById('sectorPopup');const color=event.type==='best'?'purple':event.delta<0?'green':'yellow';p.className='sector-popup '+color;popupResult.textContent=(event.delta>=0?'+':'')+event.delta.toFixed(3)+' s';requestAnimationFrame(()=>p.classList.add('show'));clearTimeout(popupTimer);popupTimer=setTimeout(()=>p.classList.remove('show'),5000)}async function refresh(){try{const d=await(await fetch('/api/telemetry',{cache:'no-store'})).json();speed.textContent=d.speed;circuit.textContent=d.circuit;driver.textContent=d.driver;gps.textContent=d.gps;sat.textContent=d.sat;delta.textContent=(d.delta>=0?'+':'')+d.delta.toFixed(3)+' s';delta.className=d.delta>=0?'delta-positive':'delta-negative';s1.textContent=d.sectors[0].toFixed(2)+' s';s2.textContent=d.sectors[1].toFixed(2)+' s';s3.textContent=d.sectors[2].toFixed(2)+' s';bestLap.textContent=fmt(d.best_lap);lastLap.textContent=fmt(d.last_lap);idealLap.textContent=fmt(d.ideal_lap);gauge(rpmTrack,rpmNeedle,d.rpm/20000*100);gauge(tempTrack,tempNeedle,(d.temp-20)/130*100);if(d.sector_event&&d.sector_event.id!==lastEventId){lastEventId=d.sector_event.id;showPopup(d.sector_event)}}catch(e){console.error(e)}}refresh();setInterval(refresh,350);
</script></body></html>
'''

def clamp(v, a, b): return max(a, min(b, v))
def simulate():
    now=time.time();phase=now/4
    state["speed"]=int(clamp(72+22*math.sin(phase)+3*math.sin(phase*2.7),35,112));state["rpm"]=int(clamp(4500+state["speed"]*82,2500,14500));state["temp"]=round(clamp(93+8*math.sin(now/18),20,150),1);state["delta"]=round(.3*math.sin(now/3),3);state["sectors"]=[round(base+.12*math.sin(now/3+i),3) for i,base in enumerate((18.42,22.18,16.77))];state["last_lap"]=round(sum(state["sectors"]),3);state["best_lap"]=min(state["best_lap"],state["last_lap"]);state["ideal_lap"]=round(min(state["ideal_lap"],state["best_lap"]-.004),3)
    if now-state["last_event_at"]>=6:
        # Demo: perdita gialla, guadagno verde, miglior settore viola. I valori popup sono delta realistici.
        sequence=[{"type":"delta","delta":+.218},{"type":"delta","delta":-.143},{"type":"best","delta":-.350}]
        state["event_id"]+=1;event=sequence[state["event_step"]];state["sector_event"]={"id":state["event_id"],**event};state["event_step"]=(state["event_step"]+1)%len(sequence);state["last_event_at"]=now
    state["updated_at"]=datetime.now().isoformat(timespec="seconds");return state
@app.route('/')
def dashboard(): return render_template_string(HTML)
@app.route('/api/telemetry')
def api(): return jsonify(simulate())
if __name__=='__main__': app.run(host='0.0.0.0',port=5001,debug=True)
